🩹 chore(ci): Use `biome check` instead of `biome format`

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -30,5 +30,5 @@ jobs:
         run: pnpm run lint:check
 
       - name: Check order in package.json
-        if: success() || failure() # Run even if linting fails
+        if: success() || failure() # Run even if the previous step fails
         run: pnpm run sort-package-json:check
