Testing phantom tests 2

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,24 +1,24 @@
-name: 🎨 Lint
+# name: 🎨 Lint
 
-on:
-  push:
-    branches:
-      - dev
-  pull_request:
+# on:
+#   push:
+#     branches:
+#       - dev
+#   pull_request:
 
-jobs:
-  style:
-    name: Check code style
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
+# jobs:
+#   style:
+#     name: Check code style
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
 
-      - name: Setup Node & Install dependencies
-        uses: ./.github/actions/setup
+#       - name: Setup Node & Install dependencies
+#         uses: ./.github/actions/setup
 
-      - name: Check linter
-        run: pnpm run lint:check
+#       - name: Check linter
+#         run: pnpm run lint:check
 
-      - name: Check order in package.json
-        if: success() || failure() # Run even if the previous step fails
-        run: pnpm run sort-package-json:check
+#       - name: Check order in package.json
+#         if: success() || failure() # Run even if the previous step fails
+#         run: pnpm run sort-package-json:check
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,92 +1,92 @@
-name: 🧑‍🔧 Test
+# name: 🧑‍🔧 Test
 
-on:
-  push:
-    branches:
-      - dev
-  pull_request:
-    paths:
-      - '.github/actions/**/*.yml'
-      - '.github/workflows/**/*.yml'
-      - 'packages/**'
-      - 'wallets/**'
+# on:
+#   push:
+#     branches:
+#       - dev
+#   pull_request:
+#     paths:
+#       - '.github/actions/**/*.yml'
+#       - '.github/workflows/**/*.yml'
+#       - 'packages/**'
+#       - 'wallets/**'
 
-jobs:
-  test-unit:
-    name: Run unit tests
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
+# jobs:
+#   test-unit:
+#     name: Run unit tests
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
 
-      - name: Setup Node & Install dependencies
-        uses: ./.github/actions/setup
+#       - name: Setup Node & Install dependencies
+#         uses: ./.github/actions/setup
 
-      - name: Build project
-        run: pnpm run build
+#       - name: Build project
+#         run: pnpm run build
 
-      - name: Run tests
-        run: pnpm run test
+#       - name: Run tests
+#         run: pnpm run test
 
-  test-e2e-headful:
-    name: Run E2E tests (headful)
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
+#   test-e2e-headful:
+#     name: Run E2E tests (headful)
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
 
-      - name: Setup Node & Install dependencies
-        uses: ./.github/actions/setup
+#       - name: Setup Node & Install dependencies
+#         uses: ./.github/actions/setup
 
-      - name: Install Foundry
-        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # pin@v1.3.1
+#       - name: Install Foundry
+#         uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # pin@v1.3.1
 
-      - name: Install Playwright dependencies
-        run: pnpm dlx playwright@1.48.2 install-deps
+#       - name: Install Playwright dependencies
+#         run: pnpm dlx playwright@1.48.2 install-deps
 
-      # For now, we only need Chromium.
-      - name: Install browsers for Playwright
-        run: pnpm dlx playwright@1.48.2 install chromium
+#       # For now, we only need Chromium.
+#       - name: Install browsers for Playwright
+#         run: pnpm dlx playwright@1.48.2 install chromium
 
-      - name: Build project
-        run: pnpm run build
+#       - name: Build project
+#         run: pnpm run build
 
-      - name: Install linux dependencies
-        run: |
-          sudo apt-get install --no-install-recommends -y \
-          xvfb
+#       - name: Install linux dependencies
+#         run: |
+#           sudo apt-get install --no-install-recommends -y \
+#           xvfb
 
-      - name: Build project
-        run: pnpm run build
+#       - name: Build project
+#         run: pnpm run build
 
-      - name: Serve MetaMask Test Dapp
-        run: |
-          pnpm run serve:test-dapp &
+#       - name: Serve MetaMask Test Dapp
+#         run: |
+#           pnpm run serve:test-dapp &
 
-      - name: Build cache (metamask)
-        run: |
-          xvfb-run pnpm run build:cache:metamask
+#       - name: Build cache (metamask)
+#         run: |
+#           xvfb-run pnpm run build:cache:metamask
 
-      - name: Build cache (phantom)
-        run: |
-          xvfb-run pnpm run build:cache:phantom
+#       - name: Build cache (phantom)
+#         run: |
+#           xvfb-run pnpm run build:cache:phantom
 
-      - name: Run E2E tests (headful)
-        run: |
-          xvfb-run pnpm run test:playwright:headful
+#       - name: Run E2E tests (headful)
+#         run: |
+#           xvfb-run pnpm run test:playwright:headful
 
-      - name: Archive Playwright report Phantom
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # pin@v4.6.0
-        if: success() || failure()
-        with:
-          name: playwright-report-headful-phantom
-          path: |
-            wallets/phantom/playwright-report-headful/
-          if-no-files-found: error
+#       - name: Archive Playwright report Phantom
+#         uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # pin@v4.6.0
+#         if: success() || failure()
+#         with:
+#           name: playwright-report-headful-phantom
+#           path: |
+#             wallets/phantom/playwright-report-headful/
+#           if-no-files-found: error
 
-      - name: Archive Playwright report Metamask
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # pin@v4.6.0
-        if: success() || failure()
-        with:
-          name: playwright-report-headful-metamask
-          path: |
-            wallets/metamask/playwright-report-headful/
-          if-no-files-found: error
+#       - name: Archive Playwright report Metamask
+#         uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # pin@v4.6.0
+#         if: success() || failure()
+#         with:
+#           name: playwright-report-headful-metamask
+#           path: |
+#             wallets/metamask/playwright-report-headful/
+#           if-no-files-found: error
